@baseUrl = http://localhost:3000 

### 

GET {{baseUrl}}

###
GET {{baseUrl}}/api/users

###
GET {{baseUrl}}/id/user

###
POST {{baseUrl}}/api/users
Content-Type: application/json

{
    "name": "alemu",
    "email": "alemusee@gmail.com",
    "age": 35

}
###
DELETE  {{baseUrl}}/api/users/6a2580834b6e999bf7a379f3 